### PR TITLE
Add reactivity to joined collections with angular-meteor

### PR DESCRIPTION
**Pull request by Lavan**
Added a new find option `reactiveJoin` that causes meteor-join to observe changes to the joined collection and update the parent.

### CODE REVIEW

**Comment by perak** [comment]
Thank you dude! 

I need to test it before merge - package is used by www.meteorkitchen.com and I need to be careful with that. Hopefully I'l merge it and publish updated package in next 12 hours.

:+1:

**Comment by Lavan** [comment]
Absolutely, I have tested it here but my setup is limited to angular so I haven't really verified it with anything else. I did try to minimize changes so hopefully you'll not have any problems.

**Comment by perak** [comment]
@Lavan this week was busy - I didn't found time to properly test, merge and publish package, but it's still on my mind :)

**Comment by Lavan** [comment]
No problem. I figured as much. :) 

On August 14, 2015 10:46:36 PM GMT+02:00, "Petar Korponaić" notifications@github.com wrote:

> @Lavan this week was busy - I didn't found time to properly test, merge
> and publish package, but it's still on my mind :) 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/perak/meteor-joins/pull/5#issuecomment-131235159

## 

Skickat från min Android-telefon med K-9 E-post. Ursäkta min fåordighet.

**Pull request closed without merging**
